TEXT = {
    "title": "Income Insights and Prediction",
    "sidebar_info": "AI system predicting personal income based on census data (education, demographics and occupation).",
    "tabs": ["📥 Input", "📤 AI Result", "📊 Data & Model Analysis"],
    "model_select": "Select Model",
    "input_header": "Enter Information",
    "age": "Age",
    "Marital_Status": "Marial Status",
    "Occupation": "Occupation",
    "Workclass": "Workclass",
    "Sex": "Gender",
    "Race": "Race",
    "edu": "Education Level (1–16)",
    "hours": "Hours per week",
    "gain": "Capital Gain (0-99999)",
    "loss": "Capital Loss  (0-4356)",
    "country": "Country",
    "predict": "Analyze & Predict",
    "not_ready": "Please enter your information first.",
    "compare": "User vs Dataset",
    "income_dist": "Income Distribution",
    "hours_chart": "Working Hours by Income",
    "age_chart": "Age Distribution by Income",
    "result_title": "Prediction Result",
    "high": "🟢 Predicted income: > 50K",
    "low": "🔴 Predicted income: ≤ 50K",
    "Age": "Age",
    "Capital Gain": "Capital Gain",
    "Capital Loss": "Capital Loss",
    "Hours per Week": "Hours per Week",
    "Education Num": "Education Level",
    "vs Avg": "vs Avg",
    "Higher than": "Higher than"
}
